name: md_api_service
description: "A Base API Service to use single Dio for multiple host and make model mapping easier."
version: 0.0.3
homepage: https://github.com/datdt-97/api_service

environment:
  sdk: ^3.0.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.7.0
  logger: ^2.4.0
  dartx: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  index_generator: ^3.4.1
